### ISSUE TITLE
Prototyping: Local storage (offline)

### ISSUE THREAD

**Issue by jimmylee** [filecoin-project/slate#104]
# Purpose

<img width="1601" alt="Screen Shot 2020-07-22 at 2 22 15 PM" src="https://user-images.githubusercontent.com/310223/88230183-ca1dde00-cc26-11ea-89f5-01e8610bd9db.png">

# Deliverable

* Ideas, complete redesigns, etc.

**Comment by uonai** [comment]
Taking a quick stab at a couple of features for offline-first functionality:

The user should be able to download their own application/web page and other applications/web pages. If we are thinking of the concept of a mood board, the user should be able to download their own mood board, maybe other mood boards as well for a social aspect. User profile and user preferences should also be available offline.

After going offline, user should be able to add images, copy, etc. When back online, these images and copy should sync with Filecoin and be hosted. I'm thinking that the syncing process should have a detailed loading indicator because there is a chance that the user has made significant changes and needs to send quite a bit of data back across the wire. 

If we want to go with a super detailed version control, we could track changes like Git and display file by file the updates the user has made while offline.

**Comment by harisbutt** [comment]
Might also be good to consider whether we want to enable offline at the file or at the moldboard level. A few things come to mind:

- Being able to see which files/slates are available for offline access
- The ability to make a file/slate available for offline access
- Maybe there is a default settings to make all files available offline?
- We'll need some kind of component to express that the application is offline (banner?)

**Comment by jimmylee** [comment]
This inspired me to create this diagram for you all !!

<img width="1618" alt="hot-and-cold" src="https://user-images.githubusercontent.com/310223/88252346-b2fce180-cc62-11ea-85f6-60647fbad119.png">

**Comment by jimmylee** [comment]
Replacement issue: https://github.com/filecoin-project/slate/issues/129
