### ISSUE TITLE
Feature: Markdown Renderer (Not editor)

### ISSUE THREAD

**Issue by jimmylee** [filecoin-project/slate#165]
# Purpose

* We want to support rendering of Markdown in Slate Media Object body
* Should support some basic things:

- [x] Todolist
- [x] Bold, Italic, Strikethrough, Underline
- [x] Links
- [x] Images as Links
- [x] Lists?
- [x] Emojis

**Comment by jimmylee** [comment]
Reminding myself to link @charlesvinette up with this one.

**Comment by charlesvinette** [comment]
I think I have a good grasp on how the text is being Processed in the body already (for @USER and #SLATELINK), I think I have a good approach planned for this - will start and share next week!
(PS: Thinking of using [https://github.com/markedjs/marked](url), any objections on using this instead of building ours?)

**Comment by jimmylee** [comment]
I don't have any objections to using `marked`!

**Comment by tarafanlin** [comment]
It occurs to me that I've always wanted to design a writing tool that allows writers to create interactive text. 
So if this issue is open and beginner-friendly, I would like to work on it at some point to understand how to building writing tools.
<img width="841" alt="Screen Shot 2020-10-28 at 11 56 34 AM" src="https://user-images.githubusercontent.com/35607644/97483459-aef0f780-1914-11eb-91f0-672dc3961a63.png">

**Comment by cwaring** [comment]
Completed in #427
