### ISSUE TITLE
Bug: delete duplicated data file not working as expected

### ISSUE THREAD

**Issue by tarafanlin** [filecoin-project/slate#264]
# Purpose

Trying to delete one of the duplicated data files, but seems to be deleting both of them.

**Comment by martinalong** [comment]
I think this one is something we're working on. Jimmy is working on making it so that you don't even see duplicate files (if you keep adding the same file you'll just see one version)

However, the fact that deleting one deletes both is normal behavior. This is because though it looks like two separate entries right now, they actually point to the same file

**Comment by tarafanlin** [comment]
Ok that makes sense thanks for explaining this :]
