### ISSUE TITLE
API is fonky, sends body in GET requests

### ISSUE THREAD

**Issue by autonome** [filecoin-project/slate#487]
# Purpose

The API docs do not say which HTTP method to use, but the URL path says "get" so I used GET.

However, it also says to put a body in there... which makes all kinds of libraries barf errors and warnings because that's not proper HTTP.

# Deliverable

API changes to either use params instead of body for GET requests, or switch to using POST with body.

API docs should also be updated to whatever path is taken.

# Dependencies

N/A

**Comment by jimmylee** [comment]
Thanks!!!

**Comment by autonome** [comment]
aha, POST does actually work, even though the examples are GET and the URL path says "get".

this *could* be fixed with docs only. but would be better to make right proper like. GET + params would be easier and clearer for things like getting list of slates.

using POST for getting things seems unnecessary.

**Comment by jimmylee** [comment]
I agree, I think the usage should be more clear so there is less ambiguity. I'll update the documentation soon!

**Comment by martinalong** [comment]
Noted! Will include this in the next design system update

**Comment by autonome** [comment]
@martinalong Hi! Can you share a link to the PR which closed this? When will it be deployed? Fixing it will break any app built against the Slate API so far, so should be communicated loudly.

**Comment by martinalong** [comment]
Hi @autonome for now this will only be an update to the docs to include "method: 'POST'" for clarity, in the interest of not breaking any apps that already use the API (the slate chrome extension included).

Made the change directly on main so there isn't a PR to link, but it's just inserting those extra lines in the doc.

The other reason I'm holding off on changing it from a GET to a POST method is because it's possible we'll add more options to these endpoints in the future which might make using GET a bit clunky.

**Comment by autonome** [comment]
Great, thanks for clarifying what the fix was, and why!

For posterity: https://github.com/filecoin-project/slate/commit/bd3cbb4c4e30cd0972496a16bc00f6afd904ebf6
