### ISSUE TITLE
database-query error

### ISSUE THREAD

**Issue by a0925260369** [filecoin-project/slate#490]
When I try to run lens with npm run dev
I got a response
```[ SERVER START     ] http://localhost:1313
connected
WEBSOCKET OPENED
(node:15656) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
{ error: true, decorator: 'GET_EVERY_SLATE' }
[ database-query ] { query: 'GET_EVERY_SLATE' }
{ error: true, decorator: 'GET_EVERY_USER' }
[ database-query ] { query: 'GET_EVERY_USER' }
```
I try to start slate and sign up a user
I got a error response
```
event - build page: /api/users/check
wait  - compiling...
event - compiled successfully
[ SLATE            ] [ 2021-01-07 03:27:21 ] DB:GET_USER_BY_USERNAME: select * from "users" where "username" = $1 limit $2 - relation "users" does not exist
[ SLATE            ] [ 2021-01-07 03:27:21 ] DB:GET_USER_BY_USERNAME
POST /api/users/check 500 43 - 573.860 ms
```
So, I try to create a table which name is users
Users check api success but create user api error
```
[ SLATE            ] [ 2021-01-07 03:29:48 ] DB:GET_USER_BY_USERNAME
POST /api/users/check 200 30 - 511.595 ms
event - build page: /api/users/create
wait  - compiling...
event - compiled successfully
POST /api/users/create 403 48 - 428.818 ms
```
How should I do? I don't know what  slate db table is correct.
Please help me. Thanks.

**Comment by martinalong** [comment]
Hi! Are you trying to access the slate database? Or set up your own database and use lens with it?
Unfortunately we can't allow people to access the slate database since that would give them access to private user information, but if you are trying to set up your **own** postgres database, the way to initialize that database properly is:

- Clone the slate repository (git clone https://github.com/filecoin-project/slate.git) 
- Add your own .env file to that repo with your own POSTGRES_ADMIN_PASSWORD, POSTGRES_ADMIN_USERNAME, POSTGRES_DATABASE, and POSTGRES_HOSTNAME
- Then run the www-setup-database and then www-seed-database scripts to create those tables with the proper format
- Make sure your lens repo also has the same .env file variables so it can access the database

**Comment by a0925260369** [comment]
Thanks, it's working for me.
