### ISSUE TITLE
Daemon Land Integration

### ISSUE THREAD

**Issue by jimmylee** [filecoin-project/slate#510]
```
user {
  username: <string>
  id: <unique-uuid-v4-or-somethingelse>
  phoneNumber: <string>, <number>
  email: <string>,
  verified: true/false,
}
```
* Don't care how you do password stuff because we'll send something to Daemon Land and you will just say it works or doesn't.
* Names of fields don't matter to me either, as long as username, id, phone number, and e-mail is represented somehow.

`getUsers()`

- returns array of all users
- unsafe, used on server only.
- `limit`
- `offset`

`signIn(username: string)`
`signOut(id: string)`
`resetPassword(email: string)`
+ send an e-mail back to reset password.

`resetPasswordFromSMS(number: string)`

`getUserById(id: string)`
- returns all user fields, most important is a unique id
- unsafe, used on server only.

`getUserByUsername(username: string)`
- returns all user fields
- unsafe, used on server only.

`createUser(user: <User>)`
- username, password, e-mail, phone number 

`updateUserById(id: string, userUpdated: <User>)`
- update username, password, e-mail, phone number
- we'll update the password the normal way through this method

`deleteUserById(id: string)`
- delete user entity by id

`confirmNewPassword(resetKey: string, password: string)`

**Comment by jimmylee** [comment]
We agreed we don't need username or delete user. @Schwartz10 I guess that also means we'll need to update our product messaging to let users know that once they create an account it wont go away.

**Comment by Schwartz10** [comment]
Looking forward to leaving more in-depth questions / feedback in this issue, but just to respond to your previous comment @jimmylee 

> I guess that also means we'll need to update our product messaging to let users know that once they create an account it wont go away

This is likely something we'll have to do on our end, not yours. On your end (since these are users bringing _their_ profiles to Slate), you actually won't have to know or care if you're creating a user or just logging them in to Slate (which really means, Slate is requesting permission from the user to access their basic profile information). When we send them an oauth email, we'll give them the "you're creating a daemon.land profile! blah blah blah about important things".
