### ISSUE TITLE
Where are the docs for `--reset-data`?

### ISSUE THREAD

**Issue by ltfschoen** [filecoin-project/slate#67]
# Purpose

At this point of the "Building an App with Filecoin from scratch - using Slate Components & Powergate" YouTube video https://youtu.be/FJjPMKRy8xQ?t=2810, Jimmy shows how you can run `npm run dev --reset-data`, which runs https://github.com/filecoin-project/slate/blob/main/package.json#L10. 
But what does the the `--reset-data` do, and why is it necessary? Is it an NPM argument that's specific to Electron?
In the README it says it clears all local files https://github.com/filecoin-project/slate#example-of-what-to-expect.
The closest I can find is `--reset-cache`.

**Comment by jimmylee** [comment]
This is going to change. But whenever you start Slate locally, you will create a folder called `.data`

In this folder there are three files after a successful boot:

```sh
library.json
local-settings.json
powergate-token
```

When you type the command `npm run dev --reset-data`, you will delete your `.data` folder and any files you added to `/public/static/` (as opposed to keeping the one from the previous session). Thank you @akuokojnr for helping me add this command.

This is because we were going to focus exclusively on an `electron` build in the beginning. Now our plan has changed and we're going to build a web hosted version that communicates with a hosted Powergate.

Because of this, all of the data stored in `library.json` `local-settings.json` and `powergate-token` will be moved to `postgres`.

**Comment by jimmylee** [comment]
I've added the documentation :)
