### ISSUE TITLE
Gallery links have no link preview

### ISSUE THREAD

**Issue by autonome** [filecoin-project/slate#713]
# Purpose
I cannot see where I am going.

Typically for an `<a href=""></a>` you can mouseover and modern browsers show a link value in the bottom left hand side of the screen.

However, Slate does not do this, so I cannot see where a click would take me in the idiomatic way of web pages on the web are webby.

# Deliverable
Mouseover an image in gallery view should show link preview in bottom left of screen.

# Dependencies
Friday night ritual of ending the week with a martini.

**Comment by martinalong** [comment]
Ahh yeah so this is because we're a single page application so the clickable things aren't actual links. Which makes it annoying that you can't command click to open in new tab or do what you're saying here. At some point we need to go through the whole codebase and convert to a component that allows us to simulate these

**Comment by martinalong** [comment]
Hey! So this has been fixed by #749. I figured out a way to maintain the benefits we get from SPA style pseudorouting (not having to reload the page and maintaining state), while still allowing things to behave normally as links. If you're curious about more details, you can see them [here](https://www.notion.so/slatesystem/How-we-handle-routing-7f42d746430c4df497ea821f2ec915d8). You should now be able to ctrl + click, right click, and see links when you hover for any tab, page route, search result, or gallery item in slate!

**Comment by autonome** [comment]
👍🏼🤩🙏🏼🆒🎉 Thanks! Def going to give the routing explainer a read.
