### ISSUE TITLE
Design: Marketing pages.

### ISSUE THREAD

**Issue by jimmylee** [filecoin-project/slate#77]
# Purpose

* @gndclouds and @tarafanlin have done some pretty cool stuff with our Typography guidelines. And things will keep getting better and better over time.
* We are lucky to have @harisbutt on the team. Our narrative for Slate should be even stronger.
* This issue describes how some of the vision, brand, and thinking manifests into real deliverables.

# Deliverable

* V0 of Landing, Community Guidelines, Terms, Privacy

# Dependencies

* https://github.com/filecoin-project/slate/issues/11
* https://github.com/filecoin-project/slate/issues/76
* https://github.com/filecoin-project/slate/issues/70
* https://github.com/filecoin-project/slate/issues/56

**Comment by gndclouds** [comment]
Are there any existing sketch or Figma docs we should be starting from?

**Comment by gndclouds** [comment]
Started a [Figma file](https://www.figma.com/file/U26YdNSJLWV8JK7h4YQl2I/Slate?node-id=0%3A1) to brainstorm a bit. Ping me if you have issues editing it.

There are currently four pages:
- 🎨 Marketing Site
- 📐 Design System Docs related to #87 
- 🧠 Brainstorming
- 🤞🏻Diagrams and Systems

**Comment by gndclouds** [comment]
New [Figma File Link](https://www.figma.com/file/DYMWe6q2zidE40zt63VqFD/Landing-Pages?node-id=0%3A1)

**Comment by tarafanlin** [comment]
### Collaboration
- [ ] top slate block
- [ ] transition animation

###  @gndclouds sections
- [ ] create slate section
- [ ] share section
- [ ] free, unlimited storage

###  @jordattebayo sections
- [ ] simple, intuitive section
- [ ] open source

### @tarafanlin sections
- [ ] private & secure 
- [ ] store files
- [ ] footer

**Comment by tarafanlin** [comment]
> ### Collaboration
> * [ ]  top slate block
> * [ ]  transition animation
> * [ ]  chrome pluin section
> 
> ### @gndclouds sections
> * [x]  create slate
> * [x]  share
> * [x]  free, unlimited storage (Pausing this section for now.)
> 
> ### @jordattebayo sections
> * [ ]  simple, intuitive
> * [ ]  open source
> 
> ### @tarafanlin sections
> * [x]  private & secure
> * [x]  store files
> * [x]  footer

Finished my part for the first pass. 
I will start working on the top slate block animation if you don't need any assistance~

**Comment by gndclouds** [comment]
Getting feedback from X00A on Tuesday (TPE Time) and working on a time to add in the chrome section from Jason.

**Comment by harisbutt** [comment]
Alright! Thanks so much for all the amazing work you all have put into this already! I'm very excited to see this come to life. After syncing with everyone today, here's where we landed with where we want to land for this milestone:

There are going to be 4 pages on the slate.host website: Landing page, Community, Download, and ToS/Guidelines. The one that matters most is obviously the landing page. Keep in mind that colors, the logo, iconography will likely change with the input from Narrative, so be sure to leave your designs open to accommodate those changes (will save us time).

@gndclouds @tarafanlin I'm going to be syncing with the Narrative folks tomorrow to get a more fleshed out version of the copy to use, but I'd like for both of you to actively solicit feedback from them and keep them in the loop as you're driving the direction of the site so that they can be more active collaborators. The more we feed them the better the outcome I think.

I created some scoping pages in your working Figma file and will continue to add the copy there as we refine it. Let me know if you have any questions!
